name: Authentication Worker Deployment
on: 
  push: 
    branches:
      - Main
jobs: 
  linux: 
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Installing Cloudflare Workers Wrangler CLI
        run: $ npm i @cloudflare/wrangler -g
      - name: Creating Config File
        env: 
          NAME: ${{ secrets.NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          REALM_APPID: ${{ secrets.REALM_APPID }}
        run: |
          echo name="$NAME" > wrangler.toml
          echo type="javascript" >> wrangler.toml
          echo account_id="$ACCOUNT_ID" >> wrangler.toml
          echo workers_dev = true >> wrangler.toml
          echo compatibility_date = "2022-05-23" >> wrangler.toml
          echo command = "npm run build" >> wrangler.toml
          echo dir = "build" >> wrangler.toml
          echo main = "./index.mjs" >> wrangler.toml
          echo format = "modules" >> wrangler.toml
          echo REALM_APPID = "$REALM_APPID" >> wrangler.toml
        shell: bash
      - name: Publishing worker
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_KEY }} wrangler publish
        

